pkg/datastore/mongodb/mongodb.go
pkg/rest/rest_server.go
pkg/rest/services/cluster.go

1. Previous list request  for list cluster and application  get empty response.
Because the iter get from "iter, err := c.ds.Find(ctx, clusterKind)"  in clusterstore.go do not have iter.next()
We fix the Find method.
The web before fix list method:
After fix:
2. Also add  GetCluster from clusterName and  use existing clusterResponse struct for return.
3. Find a wrong request  may in application/index.tsx
The url lack "/api/clusterName/"

fix list method for cluster and app

---

src/api/application.ts
src/api/devLink.ts
src/components/UISchema/index.tsx
src/extends/Group/index.tsx
src/locals/Zh/zh.json

Fix: #262 ui schema switch change, the configuration optimization

---

src/extends/Structs/index.tsx

Fixes #289 uiSchema UI bug fix
I have:
Click callback is not implemented on the left side of SplitButton. Now use the Button group to optimize

Fix: uiSchema UI splitButton optimization

---

src/pages/ApplicationList/components/AddAppDialog/index.tsx
src/pages/ApplicationList/components/GeneralConfig/index.tsx
src/pages/EnvPage/components/EnvDialog/index.tsx

Feat: hide project form item

---

src/components/UISchema/index.tsx
src/utils/common.ts

Fixes #288 make link text in the description of a parameter to by a superlink
I have:

Fix: make link text in the description of a parameter to by a superlink

---

src/interface/addon.ts
src/pages/Cluster/components/CloudServiceDialog/index.tsx
src/pages/Cluster/index.tsx

Fixes #320 create cluster add addon message show
I have:
1.dunhao Display Optimization
2.add Message closed 
3.When creating a cluster in two cases, addon information is displayed according to conditions

Fix: create cluster add addon message show

---

src/interface/application.ts
src/locals/Zh/zh.json
src/pages/ApplicationConfig/components/Components/index.less
src/pages/ApplicationConfig/components/Components/index.tsx
src/pages/ApplicationConfig/components/TraitDialog/index.tsx

Feat: support show the prompt message by the trait podDisruptive value

---

src/api/productionLink.ts
src/api/repository.ts
src/components/UISchema/index.tsx
src/extends/Group/index.tsx
src/extends/HelmChartSelect/index.tsx
src/extends/HelmChartVersionSelect/index.tsx
src/extends/HelmRepoSelect/index.tsx
src/extends/HelmValues/index.tsx
src/extends/KV/index.tsx
src/interface/application.ts
src/interface/env.ts
src/pages/ApplicationList/components/AddAppDialog/index.tsx
src/pages/EnvPage/components/EnvDialog/index.tsx
src/pages/EnvPage/components/List/index.tsx
src/utils/utils.ts

1. Support conditions in `ui schema` render. Ref oam-dev/kubevela#3461 
2. New some extend components about helm.
* HelmRepoSelect
* HelmChartSelect： Must have fields `url` 
* HelmChartVersionSelect： Must have fields `url` and `chart`
* HelmValues: Must have fields `url` 、`chart` and `version`.
I have:

Feat: support the conditions for ui schema and add some extend components about helm

---

src/layout/Application/components/AddAndEditEnvBind/index.tsx

Signed-off-by: xianyue <13651133+xianyue390348@users.noreply.github.com>
Fixes # Fix: component EnvBindPlanDialog get wrong envs
I have:

Fix: component EnvBindPlanDialog get wrong envs

---

src/utils/locale.tsx

Currently only en and zh are the only supported languages. 
If for example in reason of other browser language settings, the locales doesn't exist and the ui is not visible (after login).
As workaround it is possible to change the browser language (bad way).
The solution is to add a fallback language.
Fixes #488
I have:

Fix: Fallback local language to en if selected language does not exist 

---

public/index.html
src/components/DefinitionCode/index.tsx
src/components/ListTitle/index.less
src/components/ListTitle/index.tsx
src/components/UISchema/index.tsx
src/interface/application.ts
src/layout/index.less
src/pages/ApplicationConfig/components/ComponentDialog/index.tsx
src/pages/ApplicationConfig/components/TraitDialog/index.tsx
src/pages/ApplicationWorkflow/workflow-item/workflow-form.tsx
src/pages/EnvPage/components/List/index.less
src/pages/EnvPage/components/List/index.tsx
src/pages/TargetList/components/List/index.less
src/pages/TargetList/components/List/index.tsx

1. If there is no UI schema, default provide the YAML code editor, such as the labels trait.
2. Users could switch the native form to the YAML code editor.
This feature is very useful and resolves the native UI input constraints.
Fixes #
I have:

Feat: support edit the component/trait/workflow properties via the code

---

src/pages/Login/index.less
src/pages/Login/index.tsx

Signed-off-by: Charlie Chiang <charlie_c_0129@outlook.com>
Previously, the login process is like:
- type: admin
- Tab
- type: password
- **reach for the mouse**
- **move it to `sign in`**
- **click the mouse**
Which works, but I prefer **not** to use the mouse.
Now we are able to:
- type: admin
- Tab
- type: password
- Enter
And we are in!
Before:
After:
I have:

Feat: use keyboard navigation, press enter to login

---

.github/workflows/release.yaml

Signed-off-by: qiaozp <chivalry.pp@gmail.com>
This PR add linux/arm64 build for velaux.
We want VelaD to support more platform include linux/arm64 and darwin/arm64(M1 mac). They both need a linux/arm64 version for all images that used by VelaD.
I have:

Feat: add arm64 image build

---

Dockerfile
Dockerfile.local

https://github.com/kubevela/velaux/security/code-scanning/16063
I have:

Fix: upgrade Nginx to 1.23 and fix CVE-2022-2068

---

src/layout/CloudShell/index.less

Signed-off-by: Zhiyu Wang <cloudsky.newbis@gmail.com>
Fixes #
I have:

Fix: hidden cloudshell dialog scroll bar

---

src/pages/ApplicationRevisionList/components/Detail/index.tsx

Fix: can not show the detail of the first revision

---

src/components/TreeGraph/index.less
src/components/TreeGraph/index.tsx
src/components/TreeGraph/utils.tsx
src/interface/application.ts
src/interface/observation.ts
src/locals/Zh/zh.json
src/pages/ApplicationStatus/components/ApplicationGraph/index.tsx
src/pages/ApplicationStatus/index.tsx

status
Signed-off-by: weiy730 <weiy730@163.com>
Feat(https://github.com/kubevela/velaux/issues/536): Graphically display Component and Trait relationships and status
I have:

Feat(#536): Graphically display Component and Trait relationships and status

---

src/api/addons.ts
src/common.less
src/components/Drawer/index.less
src/interface/addon.ts
src/lib.less
src/pages/Addons/components/detail/index.less
src/pages/Addons/components/detail/index.tsx
src/pages/ApplicationConfig/components/ComponentDialog/index.tsx

Fix: enhance the drawer page of the addon

---

src/api/repository.ts
src/components/HelmValueShow/index.less
src/components/HelmValueShow/index.tsx
src/extends/HelmRepoSelect/index.tsx
src/extends/HelmValues/index.tsx
src/interface/repository.ts
src/lib.less
src/locals/Zh/zh.json
src/pages/ApplicationConfig/index.tsx

Feat: support to guide the chart configuration from the OCI registry

---

packages/velaux-ui/src/pages/ApplicationRevisionList/constants.tsx

Fixes #
Add the processing of rollback status to the version list
I have:
I don't know whether this rollback state needs a corresponding dot style. If so, what color should it be？I think light blue is good

Fix: Add the processing of rollback status to the version list

---

pkg/server/domain/service/application_test.go
pkg/server/interfaces/api/assembler/v1/do2dto.go
pkg/server/interfaces/api/dto/v1/types.go

Fixes https://github.com/kubevela/kubevela/issues/4797
I have:

Feat: deploy API return the workflow name

---

docs/apidoc/swagger.json
pkg/server/interfaces/api/addon.go
pkg/server/interfaces/api/cloudshell.go
pkg/server/interfaces/api/definition.go
pkg/server/interfaces/api/project.go
pkg/server/interfaces/api/repository.go
pkg/server/interfaces/api/user.go

This PR fixes the incompliant swagger specification that is generated by the API Server module. This will let us generate SDKs from the generated swagger.
Validate fix using [openapi generator](https://openapi-generator.tech/):
```bash
openapi-generator generate -i docs/apidoc/swagger.json -g java -o _tmp
```
Or using [swagger-cli](https://apitools.dev/swagger-cli/):
```bash
swagger-cli validate docs/apidoc/swagger.json
```
Fixes kubevela/kubevela#5536
I have:
I would be happy to pick up the related task: https://github.com/kubevela/kubevela/issues/5428 as part of GSOC.

Fix: make API Server OpenAPI compliant

---

docs/apidoc/swagger.json
e2e-test/application_test.go
packages/velaux-ui/src/locals/Zh/zh.json
packages/velaux-ui/src/pages/ApplicationList/components/CardContent/index.less
packages/velaux-ui/src/pages/ApplicationList/components/CardContent/index.tsx
packages/velaux-ui/src/pages/ApplicationList/components/SelectSearch/index.tsx
packages/velaux-ui/src/pages/ApplicationList/index.tsx
pkg/server/interfaces/api/application.go
pkg/server/interfaces/api/dto/v1/types.go

Close: #240 
support label-based selector for application management, hiding label with prefix `ux.oam.dev` and `app.oam.dev`
in table mode, fold up labels in default
expand all labels
click label tag will invoke label filter
Fixes #
I have:

Feat: support label filter for application list

---

.github/workflows/release.yaml
addon/metadata.yaml

Chore: Add the step to generate the Git-Version

---

.golangci.yml
packages/velaux-ui/src/services/plugin/PluginCache.ts
pkg/plugin/loader/loader.go
pkg/plugin/loader/loader_test.go
pkg/plugin/registry/in_memory.go
pkg/plugin/types/plugin.go
pkg/server/config/config.go
pkg/server/domain/service/definition.go
pkg/server/domain/service/plugin.go
pkg/server/interfaces/api/dto/v1/types.go
pkg/server/server.go
staticcheck.conf

Add the rule for the Golang lint.
I have:

Fix: Enhance the code style

---

docs/apidoc/swagger.json
packages/velaux-ui/src/api/repository.ts
packages/velaux-ui/src/extends/HelmChartSelect/index.tsx
packages/velaux-ui/src/extends/HelmChartVersionSelect/index.tsx
packages/velaux-ui/src/extends/HelmValues/index.tsx
pkg/server/domain/service/helm.go
pkg/server/domain/service/helm_test.go
pkg/server/interfaces/api/repository.go

Support get secret from project config for helm chart.
-->
Fixes #
I have:

Feat: support get secret from project config for helm chart

---

packages/velaux-ui/src/locals/Zh/zh.json
packages/velaux-ui/src/pages/ApplicationInstanceList/components/ContainerLog/index.tsx
packages/velaux-ui/src/pages/ApplicationLog/components/LogContainer/index.less
packages/velaux-ui/src/pages/ApplicationLog/components/LogContainer/index.tsx
packages/velaux-ui/src/utils/utils.ts

Feat: support download pod lods in velaux

---

pkg/server/domain/service/application.go
pkg/server/domain/service/application_test.go
pkg/server/interfaces/api/application.go

collect app status from all envs
Fixes #
I have:

Feat: collect app status from all envs

---

packages/velaux-ui/src/pages/ApplicationConfig/index.tsx

fix a bug : the depends on options do not show properly when adding new component after edit a component
Fixes #
I have:

Fix: The depends on options do not show properly when adding new component

---

packages/velaux-ui/src/components/UISchema/index.tsx
packages/velaux-ui/src/extends/Numbers/index.less
packages/velaux-ui/src/extends/Numbers/index.tsx

Fixes #659
In vela-core default ui-type, number array will return ui-type `Numbers`, but velaux didn't implement ui-type `Numbers`.
```golang
case "array":
if subType == "string" {
return "Strings"
}
if subType == "number" || subType == "integer" {
return "Numbers"
}
return "Structs"
```
The new ui-type preview:
Btw, i think the annotations in trait `expose` is optional, but default validate is required.
I have:

Fix: 'Numbers' ui-type in default ui schema

---

packages/velaux-ui/src/extends/Numbers/index.tsx

Fixes an issue come from #744 
I have:

Fix: Translation component is not default

---

.github/workflows/arm64-build-test.yml
.github/workflows/server-test.yml

Chore: Add a workflow to test building arm64 image

---

e2e-test/application_workflow_test.go
pkg/server/domain/service/rbac.go
pkg/server/domain/service/workflow.go
pkg/server/interfaces/api/application.go
pkg/server/interfaces/api/workflow.go

add interface to list all workflow records from an env
Fixes #
I have:

Feat: add interface to list all workflow records from an env

---

pkg/server/domain/service/workflow.go
pkg/server/event/sync/cr2ux.go

Fix: fix sync when restarting the application

---

addon/metadata.yaml
addon/resources/server.cue
packages/velaux-data/src/types/menus.ts
packages/velaux-ui/src/layout/Header/index.tsx
packages/velaux-ui/src/layout/LeftMenu/index.tsx

Move the grafana navigation from the top bar to the extension workspace.
I have:

Feat: Move the grafana navigation to the extension workspace

---

packages/velaux-data/package.json
packages/velaux-ui/package.json
packages/velaux-ui/src/components/UISchema/index.tsx
packages/velaux-ui/src/pages/ApplicationConfig/components/ComponentDialog/index.less
packages/velaux-ui/src/pages/ApplicationConfig/components/ComponentDialog/index.tsx
packages/velaux-ui/src/pages/ApplicationWorkflowStatus/components/WorkflowRecord/index.less
packages/velaux-ui/src/pages/ApplicationWorkflowStatus/index.tsx
pkg/server/domain/service/workflow.go

Fix: The latest workflow records are not loaded

---

go.mod
pkg/features/server.go
pkg/server/server.go
pkg/server/utils/filters/gzip.go
pkg/server/utils/filters/gzip_test.go
pkg/server/utils/filters/js-cache.go
pkg/server/utils/filters/js-cache_test.go

Fixes #771
Before, the static files don't compress. Loading the core JS file takes a long time. 
> Testing on local, the network is very fast.
After adding the gzip compress:
The content size reduces by 75%.
After the first request, other requests will hit the cache.
The time reduces by 35%.
I have:

Feat: Support to compress and cache the static files

---

packages/velaux-ui/src/pages/ApplicationWorkflowStudio/components/CanarySetting/index.tsx
packages/velaux-ui/src/pages/ApplicationWorkflowStudio/index.tsx

Fix: Add the prepare step for the canary workflow

---

addon/metadata.yaml
addon/resources/server.cue
docs/contributing/how-to-build-plugin.md
docs/contributing/velaux.md
docs/plugins/backend-kube-api-allow-route/plugin.json
docs/plugins/backend-kube-api-node/plugin.json
docs/plugins/backend-kube-api/plugin.json
docs/plugins/backend-kube-service/plugin.json
docs/plugins/frontend/plugin.json

Chore: Add the guide for the plugin developer

---

go.mod
go.sum
pkg/server/domain/service/application.go
pkg/server/domain/service/workflow.go
pkg/server/event/sync/convert/convert.go

Fix: fix rollback sync and terminate case

---

packages/velaux-ui/src/extends/MemoryNumber/index.tsx

Fix: Modifying Memory Units

---

packages/velaux-ui/src/pages/ApplicationInstanceList/components/Header/index.tsx
packages/velaux-ui/src/pages/ApplicationInstanceList/index.tsx
packages/velaux-ui/src/pages/ApplicationStatus/index.tsx
packages/velaux-ui/src/pages/ApplicationWorkflowStatus/index.tsx

Fix: Check the permission before request the compare API

---

pkg/server/domain/service/user.go

1. fix panic:
2. shorten the indent
Fixes #
I have:

Fix: list user projects panic

---

pkg/server/infrastructure/datastore/mongodb/mongodb.go

Fix: mongodb adds data model to set update time

---

pkg/server/server.go
pkg/server/utils/filters/gzip.go
pkg/server/utils/filters/js-cache.go
pkg/server/utils/filters/js-cache_test.go

Ref https://github.com/kubevela/velaux/issues/811
This PR prevent caching non-200 http response in JsCache. Add some logs to track the issue better.
Fixes #
I have:

Fix: prevent caching js when http code isn't 200

---

packages/velaux-ui/src/components/UISchema/index.less
packages/velaux-ui/src/components/UISchema/index.tsx

Fixes #
In creating an application, advanced parameters should be left aligned：
I have:

Fix: Modify advanced parameters to align left

---

Makefile
docs/contributing/velaux.md

This PR adds `make setup-test-server` command to makefile for installing kubebuilder and its dependency tools to .
Also contribution docs is modified accordingly.
Fixes #
I have:

Chore: adds steps for installing kubebuilder and its dependency tools to makefile

---

go.mod
go.sum
pkg/server/config/config.go
pkg/server/infrastructure/datastore/mysql/mysql.go
pkg/server/server.go

This PR adds MySQL driver for the VelaUX api-server
Fixes #
I have:

Feat: add MySQL database driver

---

packages/velaux-ui/src/pages/ApplicationConfig/components/TriggerList/index.less
packages/velaux-ui/src/pages/ApplicationConfig/components/TriggerList/index.tsx

This PR adds curl commands for all types of custom triggers.
https://github.com/kubevela/velaux/assets/80708727/ed8e0c03-58b5-4c54-a4ab-b8b15577690c
Fixes #834 
I have:

Feat: add info about other custom triggers

---

packages/velaux-ui/src/pages/ApplicationList/components/CardContent/index.tsx

Fixes https://github.com/kubevela/velaux/issues/823
I have:

Fix: application table view crash when app have no labels

---

.github/workflows/release.yml
pkg/plugin/router/router.go
pkg/plugin/router/router_test.go
pkg/plugin/types/plugin.go
pkg/server/server.go

Depracate acr, improve code readability. 
I have:

Chore: remove acr image

---

pkg/server/infrastructure/datastore/mongodb/mongodb.go

Feat: adds support of mongodb urls with prefix `mongodb+srv://` 

---

go.mod
go.sum
pkg/server/infrastructure/clients/kubeclient.go

Fix: cloudshell scheme not found

---

packages/velaux-ui/src/components/UISchema/index.tsx
packages/velaux-ui/src/extends/Group/index.tsx

the two group of properties ,as show in the picture, can't coexist
otherwise it will has an error when deploy app
So, we customized the uiSchema as follows
But the customized uiSchema can't show properly
Fixes #
I have:

Fix: customized uiSchema can't show properly

---

pkg/server/domain/service/target.go

In CreateTarget, a default cluster should be created if cluster is not speicified in the request. However, cluster is only applied to the _request_ variable, not the actual created _target_ . With this fix, the created _target_ would have default _cluster_
Fixes #
I have:

Fix: applied default cluster to created target

---

.dockerignore
Makefile
makefiles/const.mk
pkg/plugin/proxy/static_server_proxy.go
pkg/plugin/types/plugin.go
pkg/server/domain/repository/env.go
pkg/server/domain/repository/target.go
pkg/server/domain/service/application.go
pkg/server/domain/service/authentication.go
pkg/server/domain/service/cloudshell.go
pkg/server/domain/service/cluster.go
pkg/server/domain/service/env.go
pkg/server/domain/service/pipeline.go
pkg/server/domain/service/project.go
pkg/server/domain/service/rbac.go
pkg/server/domain/service/target.go
pkg/server/domain/service/webhook.go
pkg/server/domain/service/workflow.go
pkg/server/domain/service/workflow_test.go
pkg/server/event/collect/system_info_collect.go
pkg/server/event/event.go
pkg/server/event/event_test.go
pkg/server/infrastructure/datastore/datastore.go
pkg/server/infrastructure/datastore/sqlnamer/sqlnamer.go
pkg/server/interfaces/api/dto/v1/types.go
pkg/server/interfaces/api/workflow.go
pkg/server/server.go
pkg/server/utils/bcode/bcode.go

Fix: CodeQL job fails

---

pkg/server/domain/service/definition.go

The meaning of additionalProperties.has is wrongly used. Then default uischema of gateway is wrongly generated.
Ref: https://swagger.io/docs/specification/data-models/dictionaries/
Fixes https://github.com/kubevela/kubevela/issues/6165
I have:

Fix: additionalPropertis in openapi schema converted to uischema wrongly

---

pkg/server/interfaces/api/application.go
pkg/server/interfaces/api/cloudshell.go
pkg/server/interfaces/api/cluster.go
pkg/server/interfaces/api/definition.go
pkg/server/interfaces/api/plugin.go
pkg/server/interfaces/api/target.go

Some API have returns200 in the response, which would overwrite the desired API response format with a SimpleResponse object, which is a bug on the server side. This MR removes the `returns200` field so that each API response will respond data in the wanted format
Fixes #
I have:

Fix: incorrect API response mark

---

pkg/server/domain/service/config.go
pkg/server/domain/service/config_test.go
pkg/server/domain/service/helm.go

Signed-off-by: Qiaozp <qiaozhongpei.qzp@alibaba-inc.com>
The logic in `GetConfig` interface will return `extract auth info from secret error` when the configured helm repo is from global config. 
Fixes #
I have:

Fix: fail to get global helm config secret

---

pkg/server/config/config.go
pkg/server/domain/service/workflow.go
pkg/server/event/sync/worker.go
pkg/server/server.go

Currently if we step-by-step debug the server for a longer time than `RenewDeadline` of leader election, the program will exit. This PR support a flag to switch this behavior.
If server starts with `--exit-on-lost-leader=false`, the server will keep running and try to become leader. If the debugging program is the only replica, it will become leader soon.
This PR also add a retry mechanism for application workflow sync. The max failure times is 5.
Fixes #
I have:

Feat: support exit-on-lost-leader flag

---

.github/workflows/server-test.yml
pkg/server/infrastructure/datastore/datastore_test.go
pkg/server/infrastructure/datastore/mysql/mysql.go
pkg/server/infrastructure/datastore/postgres/postgres.go
pkg/server/infrastructure/datastore/sql/driver.go

1. unify sql data driver implementation
2. Remove opengause test for upstream remove the action
Fixes #
I have:

Chore: unify sql data driver implementation

---

pkg/server/infrastructure/datastore/mysql/mysql.go
pkg/server/infrastructure/datastore/postgres/postgres.go

Fix: Enables translate error property of `gorm`

---

pkg/server/domain/service/util.go
pkg/server/interfaces/api/application.go
pkg/server/interfaces/api/target.go

fix some typo errors.
I have:
No.

Fix: fix some typo errors

---

docs/apidoc/swagger-3.0.json
docs/apidoc/swagger.json
packages/velaux-ui/src/pages/Cluster/index.tsx
pkg/server/interfaces/api/plugin.go
pkg/server/interfaces/api/repository.go

* Update swagger.json by `make build-swagger`.
* Returns a predefined structure instead of a map object to avoid Swagger being unable to generate code correctly
* Delete duplicate runtimes_cluster parameter definition to avoid the code constructed by swagger being unusable
* Add swagger 3.0.json to facilitate developers debugging APIs on the swagger UI (BearerAuth only available in swagger 3.0+).
Fixes #713 
I have:

Fix: fix swagger.json

---

.github/workflows/server-test.yml
pkg/server/domain/service/authentication.go

1. "Fixes #903": SSO user default project not getting set because the username vela_user.name doesn't have the same length as the username FK in vela_project_user 
This means users logging in have no permissions whatsoever unless someone manually adds it.
2. The e2e tests were failing due to k3s version 1.21 not being available. I've removed the version from the matrix
I have:

Fix: Username length in projects users to match users

---

packages/velaux-ui/src/pages/Addons/components/detail/index.tsx

Fix(addons): Align Button with Title in AddonDetailDialog

---

packages/velaux-ui/src/components/HelmValueShow/index.tsx

- Added custom width (60vw) to Helm values.yaml dialog for better visibility.
- Enabled close modes: 'close' and 'mask' to improve user experience.
Fixes #851
I have:

Feat: improve Helm charts values.yaml popup

---

packages/velaux-ui/src/pages/ApplicationConfig/components/TraitDialog/index.tsx

- Addressed the issue where default values for traits (including "cpuscaler", "hpa", "resource", "k8s-update-strategy") were not being set properly.
Fixes #650
I have:

Fix: Set default values for traits in VelaUX

---

packages/velaux-ui/src/pages/Cluster/components/AddClusterDialog/index.tsx

- Added optional chaining to safely access cluster details in `AddClusterDialog`.
This fix addresses the issue where the page crashes when trying to load details for an inaccessible cluster.
Fixes #685
I have:

Fix: Prevent crashes when accessing cluster details
