- go.mod
- go.sum
- pkg/commands/server.go
- pkg/datastore/datastore.go
- pkg/restapi/restapi.go
ref https://github.com/oam-dev/velacp/issues/3 https://github.com/oam-dev/velacp/issues/5
> run server command and add restapi and datastore abstractions

- ui/config/routes.ts
- ui/mock/catalog.ts
- ui/src/models/useCatalogs.ts
- ui/src/pages/Catalog/index.tsx
- ui/src/pages/PackageList/components/UpdateForm.tsx
- ui/src/pages/PackageList/index.tsx
- ui/src/pages/User/login/index.tsx
- ui/src/services/API.d.ts
- ui/src/services/catalog.ts
Signed-off-by: Hongchao Deng <hongchaodeng1@gmail.com>
> add packages page

- Makefile
- pkg/datastore/datastore.go
- pkg/datastore/mongodb/mongodb.go
- pkg/datastore/storeadapter/clusterstore.go
- pkg/rest/apis/types.go
- pkg/rest/rest_server.go
- pkg/rest/services/cluster.go
about #88 
- DB add update data method
- implement some store level method
- add create/update/delete cluster API
- add get all clusters name API
> feat: add cluster api

- package-lock.json
- package.json
- pkg/rest/rest_server.go
- pkg/rest/services/application.go
- pkg/rest/services/definitions.go
- ui/src/pages/Application/InputForm/components/CapabilityForm/index.tsx
- ui/src/pages/Application/index.tsx
- ui/src/services/kubevela/applicationapi.ts
Signed-off-by: zhuhuijun <zhuhuijunzhj@gmail.com>
> fix(app) fix app ui and api

- docs/contributing/backend.md
install protoc plugin protoc-gen-go
> update contributing docs

- CONTRIBUTING.md
- OWNERS
> add CONTRIBUTING Guide and owner file

- ui/src/app.tsx
> turn off watermark

- .github/workflows/release.yml
- Makefile
> add release action pipeline

- Makefile
> fix release make command

- src/interface/observation.ts
- src/pages/ApplicationInstanceList/components/PodDetail/index.tsx
- src/pages/ApplicationInstanceList/index.tsx
tidy up the view api, please wait https://github.com/oam-dev/kubevela/pull/2779 be merged
> Feat: update the app resources query api

- src/api/application.ts
- src/layout/Application/components/Header/index.less
- src/layout/Application/components/Header/index.tsx
- src/layout/Application/index.tsx
- src/locals/En/en.json
- src/locals/Zh/zh.json
- src/model/workflow.js
- src/pages/ApplicationWorkflow/entity.tsx
- src/pages/ApplicationWorkflow/workflow-component/index.tsx
- src/pages/ApplicationWorkflow/workflow-item/index.tsx
- src/pages/ApplicationWorkflow/workflow-item/workflow-form.tsx
Feat: workflow crud and fix dataflow
> Feat: workflow crud and fix dataflow

- src/extends/KV/index.tsx
- src/extends/Structs/index.tsx
- src/interface/application.ts
- src/pages/Addons/components/detail/index.tsx
- src/pages/ApplicationConfig/components/TraitDialog/index.tsx
> Fix: fix the remove item bug in KV and Structs component

- .github/pr-title-checker-config.json
- .github/workflows/commit-lint.yml
> Chore: add pr title check action

- src/layout/Application/components/WorkflowStep/index.tsx
- src/model/workflow.js
- src/pages/ApplicationWorkflow/workflow-component/index.tsx
- src/pages/ApplicationWorkflow/workflow-item/index.tsx
- src/pages/ApplicationWorkflow/workflow-item/workflow-form.tsx
> Feat: support set and cancel workflow default attribute

- src/interface/observation.ts
- src/pages/ApplicationInstanceList/components/Hearder/index.tsx
- src/pages/ApplicationInstanceList/components/StatusShow/index.tsx
- src/pages/ApplicationInstanceList/index.tsx
- src/pages/Cluster/components/CloudServiceDialog/index.tsx
> Feat: optimize data presentation

- src/api/addons.ts
- src/components/UISchema/index.tsx
- src/pages/Addons/components/detail/index.tsx
> Feat: support upgrade addon

- .github/workflows/release.yaml
- Dockerfile
- package.json
- src/locals/Zh/zh.json
- src/pages/ApplicationConfig/components/TraitDialog/index.tsx
> Chore: change release action config

- src/components/ListTitle/index.tsx
- src/components/UISchema/index.tsx
- src/extends/KV/index.tsx
- src/pages/Cluster/components/AddClustDialog/index.tsx
> Feat: support the additional parameter in KV component

- .github/PULL_REQUEST_TEMPLATE.md
> Chore: add PR template file

- src/api/application.ts
- src/interface/deliveryTarget.ts
- src/layout/Application/components/AddAndEditEnvBind/index.tsx
- src/pages/ApplicationInstanceList/components/Hearder/index.tsx
- src/pages/ApplicationInstanceList/index.tsx
- src/pages/DeliveryTargetList/components/List/index.tsx
> Fix: service endpoint did not show and show target cluster alias

- src/extends/Strings/index.tsx
Fix: uiSchema CMD enter optimization
Fixes #
I have:
> Fix: uiSchema CMD enter optimization

- src/components/UISchema/index.tsx
- src/extends/SecretKeySelect/index.tsx
- src/extends/SecretSelect/index.tsx
Fixes: uiSchema SecretKeySelect init value optimization
I have:
> Fix: uiSchema SecretKeySelect init value optimization

- public/index.html
- src/api/cluster.ts
- src/components/StatusShow/index.tsx
- src/components/UISchema/index.tsx
- src/extends/Group/index.tsx
- src/extends/HelmValues/index.tsx
- src/interface/application.ts
- src/model/uischema.js
- src/pages/Addons/components/detail/index.tsx
- src/pages/ApplicationConfig/components/EditProperties/index.tsx
- src/pages/ApplicationInstanceList/components/Hearder/index.tsx
- src/pages/ApplicationList/components/AddAppDialog/index.tsx
- src/pages/Cluster/components/CardContent/index.tsx
- src/utils/errors.ts
Fixes #279 
Fixes #278 
Fixes #268 
Fixes #259
I have:
> Fix: the process of disabling addon lacks state control

- src/model/addons.js
- src/pages/Addons/components/registry-manage/index.tsx
- src/pages/Addons/components/search/index.tsx
- src/pages/Addons/index.tsx
- src/pages/ApplicationConfig/components/EditProperties/index.tsx
> Fix: adapt to the registry list API changes

- src/interface/addon.ts
- src/model/addons.js
- src/pages/Addons/components/card-conten/index.tsx
- src/pages/Addons/components/detail/index.tsx
- src/pages/Addons/components/registry-manage/index.tsx
- src/pages/Addons/index.tsx
- src/pages/ApplicationList/components/CardContent/index.tsx
- src/pages/Cluster/components/CardContent/index.tsx
Fixes #299 
I have:
/cc @zzxwill
> Feat: support add experimental addon registry

- public/index.html
- src/layout/index.less
Fixes #302  optimize the menu style on the mobile terminal
I have:
> Fix: optimize the menu style on the mobile terminal

- package.json
- src/api/addons.ts
- src/api/observation.ts
- src/api/request.ts
- src/interface/addon.ts
- src/interface/observation.ts
- src/layout/Content/index.tsx
- src/model/addons.js
- src/pages/Addons/components/detail/index.tsx
- src/pages/Addons/index.tsx
- src/pages/ApplicationInstanceList/components/ContainerLog/index.less
- src/pages/ApplicationInstanceList/components/ContainerLog/index.tsx
- src/pages/ApplicationInstanceList/components/PodDetail/index.tsx
- src/pages/ApplicationInstanceList/index.tsx
- src/utils/common.ts
- yarn.lock
-[x] support show log and grafana dashboard link after enabling observability addon.
-[x] default show log link, support query container log.
Fixes #286
I have:
/cc @zzxwill
> Feat: support show log and grafana dashboard link

- src/components/UISchema/index.tsx
- src/pages/ApplicationList/components/AddAppDialog/index.tsx
- src/pages/ApplicationWorkflow/workflow-item/index.tsx
> Fix: uischame render value error and env value error

- src/pages/ApplicationInstanceList/index.tsx
> Fix: fix undefined bug

- src/components/EnvPlan/index.tsx
- src/interface/application.ts
- src/layout/Application/components/AddAndEditEnvBind/index.tsx
- src/layout/Application/components/EnvTabs/index.tsx
- src/layout/LeftMenu/menu.js
- src/pages/ApplicationConfig/components/TriggerList/index.less
- src/pages/ApplicationConfig/components/TriggerList/index.tsx
- src/pages/ApplicationConfig/index.tsx
- src/pages/ApplicationList/components/AddAppDialog/index.tsx
- src/pages/ApplicationList/components/CardContent/index.tsx
- src/pages/ApplicationRevisionList/components/List/index.tsx
- src/pages/ApplicationRevisionList/index.tsx
- src/pages/EnvPage/components/EnvDialog/index.tsx
- src/pages/EnvPage/components/List/index.tsx
- src/pages/EnvPage/index.tsx
> Feat: change env to environment

- src/components/UISchema/index.tsx
- src/extends/Structs/index.tsx
- src/layout/Application/components/AddAndEditEnvBind/index.tsx
- src/pages/ApplicationInstanceList/components/Hearder/index.tsx
- src/pages/ApplicationList/components/AddAppDialog/index.tsx
- src/pages/ApplicationWorkflow/workflow-component/index.tsx
- src/pages/ApplicationWorkflow/workflow-item/index.tsx
- src/pages/ApplicationWorkflow/workflow-item/workflow-form.tsx
> Feat: support nested form  parameter verification

- src/pages/TargetList/components/TargetDialog/index.tsx
Fixes #321  terminated workflow's suspend status is incorrect
I have:
> Fix: remove ZONE and PVC parameter

- src/interface/addon.ts
- src/pages/ApplicationInstanceList/components/PodDetail/index.tsx
The metrics and logging doesn't show correctly
Fixes #
I have:
> Fix: display its metrics and logging in Dashboard

- src/layout/Application/components/AddAndEditEnvBind/index.tsx
- src/layout/index.less
- src/pages/ApplicationList/components/AddAppDialog/index.tsx
- src/pages/ApplicationList/components/GeneralConfig/index.tsx
- src/pages/ApplicationList/index.tsx
Fixes #324 add create env in application create and details envbings
I have:
> Fix: add create env in application create and details envbings

- public/mock/getPayloadTypes.json
- src/api/application.ts
- src/api/devLink.ts
- src/api/payload.ts
- src/api/productionLink.ts
- src/common.less
- src/pages/ApplicationConfig/components/TriggerDialog/index.tsx
- src/pages/ApplicationConfig/components/TriggerList/index.tsx
- src/pages/ApplicationConfig/index.tsx
Fixes #315 application details add create and delete trigger
I have:
> Fix: application details add create and delete trigger

- src/api/observation.ts
- src/interface/observation.ts
- src/pages/ApplicationInstanceList/components/Hearder/index.tsx
- src/pages/ApplicationInstanceList/index.tsx
> Fix: add query the application service endpoint

- src/layout/Application/components/EnvTabs/index.tsx
- src/pages/ApplicationConfig/index.tsx
> Fix: typo of baseline config

- src/layout/Application/components/EnvTabs/index.less
- src/layout/Application/components/EnvTabs/index.tsx
- src/pages/ApplicationConfig/components/TriggerDialog/index.tsx
> Fix: clicking on the blank area cannot switch tab

- src/api/config.ts
> Fix: the api path is invalid

- .github/workflows/back-port.yaml
- .github/workflows/issue-commands.yml
Signed-off-by: FogDong <dongtianxin.tx@alibaba-inc.com>
Fixes #
I have:
/cc @barnettZQG
> Feat: add backport

- package.json
- src/components/UISchema/index.tsx
- src/interface/application.ts
- src/layout/TopBar/index.tsx
- src/model/workflow.js
- src/pages/ApplicationWorkflow/entity.tsx
- src/pages/ApplicationWorkflow/index.tsx
- src/pages/ApplicationWorkflow/workflow-component/index.tsx
- src/pages/ApplicationWorkflow/workflow-edge/index.less
- src/pages/ApplicationWorkflow/workflow-edge/index.tsx
- src/pages/ApplicationWorkflow/workflow-item/index.tsx
- src/pages/ApplicationWorkflow/workflow-item/workflow-form.tsx
- src/pages/ApplicationWorkflow/workflow-node/index.less
- src/pages/ApplicationWorkflow/workflow-node/index.tsx
- yarn.lock
> Feat: refactor the editing mode of the workflow

- src/layout/LeftMenu/index.less
- src/layout/LeftMenu/index.tsx
Added version info from package.json to the sidebar
Fixes #343 
I have:
> Feat: Added version info into sidebar

- package.json
- src/layout/index.less
> Feat: change version

- src/components/UISchema/index.tsx
- src/extends/Group/index.less
- src/extends/InnerGroup/index.less
- src/extends/SpectionGroup/index.less
- src/extends/SpectionGroup/index.tsx
- src/extends/Structs/index.less
- src/extends/Structs/index.tsx
- src/layout/Application/components/EnvTabs/index.less
- src/pages/ApplicationInstanceList/index.tsx
Fixes #337 uiSchema structs optimization
I have:
> Fix: uiSchema structs optimization

- src/components/UISchema/index.tsx
- src/extends/InnerGroup/index.less
- src/extends/SpectionGroup/index.less
- src/extends/SpectionGroup/index.tsx
- src/extends/Structs/index.less
- src/extends/Structs/index.tsx
- src/layout/Application/components/EnvTabs/index.less
- src/pages/ApplicationInstanceList/index.tsx
- src/pages/TargetList/components/Namespace/index.less
- src/pages/TargetList/components/Namespace/index.tsx
- src/pages/TargetList/components/TargetDialog/index.tsx
> Chore: merge main to 1.2

- src/pages/ApplicationList/components/AddAppDialog/index.tsx
Fixes #352 compoent type add filter search and group
I have:
> Fix: compoent type add filter search and group

- .github/workflows/ci.yaml
- .github/workflows/image-scan.yaml
> Chore: add the image scan action

- src/extends/Structs/index.tsx
> Fix: optimize the total number of parameters calculation algorithm.

- src/components/StatusShow/index.tsx
> Fix: change app condition show

- package.json
> Feat: change the version in package.json

- src/pages/ApplicationInstanceList/components/PodDetail/index.tsx
Signed-off-by: Zhiyu Wang <cloudsky.newbis@gmail.com>
Fixes #
I have:
> Feat: add pod restarts count

- src/components/StatusShow/index.tsx
- src/layout/Application/components/EnvTabs/index.tsx
- src/layout/Application/components/Menus/index.tsx
- src/layout/Content/index.tsx
- src/pages/ApplicationInstanceList/components/Header/index.tsx
- src/pages/ApplicationInstanceList/index.tsx
- src/pages/ApplicationRevisionList/components/List/index.tsx
- src/pages/ApplicationStatus/index.tsx
- src/utils/utils.ts
This PR adds a new page to show the application status.
I have:
> Feat: add show app status page

- src/pages/Cluster/components/CloudServiceDialog/index.less
- src/pages/Cluster/components/CloudServiceDialog/index.tsx
Fixes #378 
I have:
The root cause of the problem should be visual error caused by no pagination.
> Fix: cloud list can't be  scrolling down

- src/layout/Application/components/Menus/index.tsx
- src/layout/Content/index.tsx
- src/locals/Zh/zh.json
- src/pages/ApplicationConfig/components/ComponentDialog/index.tsx
- src/pages/ApplicationLog/components/LogContainer/index.less
- src/pages/ApplicationLog/components/LogContainer/index.tsx
- src/pages/ApplicationLog/index.tsx
Fixes #application detail add logs page
I have:
> Feat: application detail add logs page

- src/api/application.ts
- src/interface/application.ts
- src/pages/ApplicationConfig/components/TraitDialog/index.tsx
- src/pages/ApplicationConfig/index.tsx
> Feat: get the suitable trait definitions by appliedWorkload

- src/api/productionLink.ts
- src/api/users.ts
- src/components/ListTitle/index.tsx
- src/interface/user.ts
- src/layout/Content/index.tsx
- src/layout/LeftMenu/menu.js
- src/locals/Zh/zh.json
- src/pages/ApplicationLog/components/LogContainer/index.tsx
- src/pages/Users/components/CreateUser/index.tsx
- src/pages/Users/components/ResetPassWordDialog/index.tsx
- src/pages/Users/components/SelectSearch/index.less
- src/pages/Users/components/SelectSearch/index.tsx
- src/pages/Users/index.less
- src/pages/Users/index.tsx
- src/utils/common.ts
Fixes # userManager develop
I have:
> Feat: userManager page implements

- src/api/request.ts
> Fix: status 401,  redirect to login page

- src/api/addons.ts
- src/extends/HelmRepoSelect/index.tsx
- src/interface/addon.ts
- src/layout/LeftMenu/menu.js
- src/locals/Zh/zh.json
- src/pages/Addons/components/detail/index.less
- src/pages/Addons/components/detail/index.tsx
- src/pages/Addons/components/registry-manage/index.tsx
- src/pages/Addons/components/search/index.tsx
- src/pages/ApplicationList/components/AddAppDialog/index.tsx
- src/pages/ApplicationList/components/GeneralConfig/index.tsx
- src/pages/Cluster/index.tsx
- src/pages/Login/index.tsx
- src/pages/ProjectMembers/components/MemberDialog/index.tsx
- src/pages/Users/components/CreateUser/index.tsx
- src/pages/Users/components/ResetPassword/index.tsx
- src/pages/Users/index.tsx
- src/utils/common.ts
> Feat: support set addon cluster and version

- Dockerfile
- entrypoint.sh
- web.conf
Signed-off-by: FogDong <dongtianxin.tx@alibaba-inc.com>
Feat: add dex config
I have:
/cc @barnettZQG
> Feat: add dex config

- .eslintrc.js
- Dockerfile
- config/webpack.config.js
- package.json
- src/declaration.d.ts
- src/layout/LeftMenu/index.less
- src/layout/LeftMenu/index.tsx
- src/layout/TopBar/index.tsx
- src/model/user.ts
- src/pages/Addons/components/detail/index.tsx
> Feat: change and show version

- src/api/config.ts
- src/components/PlatformSetting/index.tsx
- src/interface/system.ts
- src/layout/TopBar/index.tsx
- src/locals/Zh/zh.json
- src/pages/Users/components/ResetPassword/index.tsx
- src/pages/Users/index.less
- src/pages/Users/index.tsx
> Feat: support update the platform configuration

- src/api/repository.ts
- src/extends/HelmRepoSelect/index.tsx
- src/model/uischema.js
- src/pages/ApplicationConfig/components/ComponentDialog/index.tsx
- src/pages/ApplicationConfig/components/TraitDialog/index.tsx
- src/pages/ApplicationConfig/index.tsx
- src/pages/ApplicationList/components/AddAppDialog/index.tsx
> Fix: query helm repos without project name

- src/pages/Integrations/components/CreateIntegrationDialog/index.tsx
> Fix: disable type selector where option length is 1

- Dockerfile.local
- src/layout/Integrations/components/Menu/index.tsx
- src/layout/Integrations/index.tsx
- src/pages/Integrations/components/CreateIntegrationDialog/index.tsx
- src/pages/Integrations/index.tsx
- src/pages/ProjectSummary/index.tsx
> Feat: change show alias

- src/interface/addon.ts
- src/locals/Zh/zh.json
- src/pages/Addons/components/registry-manage/index.tsx
add addons gitlab support
Fixes #
I have:
> Feat: add addons gitlab support

- src/api/request.ts
- src/locals/Zh/zh.json
- src/utils/common.ts
- src/utils/errors.ts
- src/utils/resetLogin.ts
- src/utils/storage.ts
Fixes #refresh token handler implements
I have:
> Feat: refresh token handler implements

- src/pages/Integrations/index.less
- src/pages/Integrations/index.tsx
Fixes #configType add status info
I have:
> Feat: configType page add status info show

- src/extends/Structs/index.tsx
- src/pages/Addons/components/detail/index.tsx
- src/pages/Addons/components/registry-manage/index.tsx
- src/pages/Addons/index.tsx
- src/pages/Cluster/components/CardContent/index.tsx
- src/pages/Cluster/components/CloudServiceDialog/index.tsx
- src/pages/Cluster/index.tsx
- src/pages/EnvPage/components/List/index.tsx
- src/pages/EnvPage/index.tsx
- src/pages/Integrations/index.tsx
- src/pages/Roles/index.tsx
- src/pages/TargetList/components/List/index.tsx
- src/pages/TargetList/index.tsx
- src/pages/Users/index.tsx
Fixes #Feat: user and roles add button permission
I have:
> Feat: some pages add  button permission

- src/api/project.ts
- src/interface/integrations.ts
- src/locals/Zh/zh.json
- src/pages/Integrations/index.tsx
- src/pages/ProjectSummary/components/Integrations/index.less
- src/pages/ProjectSummary/components/Integrations/index.tsx
- src/pages/ProjectSummary/components/Targets/index.tsx
- src/pages/ProjectSummary/index.tsx
Fixes #project integration implements
I have:
> Feat: project integration page implements

- src/pages/ApplicationConfig/index.tsx
> Fix: the cloud service application can not show the components list

- src/components/UISchema/index.tsx
- src/extends/HelmRepoSelect/index.tsx
> Feat: automatically asign a value for the secretRef field.

- package.json
- src/api/request.ts
- src/components/UISchema/index.tsx
- src/interface/application.ts
- src/locals/Zh/zh.json
- src/pages/ApplicationRevisionList/components/List/index.tsx
- src/pages/ApplicationStatus/index.tsx
> Fix: change applied resources list

- src/components/PlatformSetting/index.tsx
- src/layout/TopBar/index.tsx
- src/pages/Integrations/index.less
- src/pages/ProjectSummary/components/Integrations/index.less
Fixes #platform router jump update
I have:
> Fix: platform router jump update

- src/pages/ApplicationStatus/index.tsx
> Fix: the local cluster name not shown

- .github/workflows/ci.yaml
> Chore: change the branches

- src/utils/common.ts
> Fix: refresh token can not work

- src/pages/Login/index.less
- src/pages/Login/index.tsx
> Fix: support login i18n

- src/locals/Zh/zh.json
- src/pages/CallBackPage/index.tsx
> Fix: sso dex error, guide users to login page

- src/components/Item/index.tsx
- src/components/PlatformSetting/index.tsx
- src/interface/system.ts
- src/layout/TopBar/components/EditPlatFormUserDialog/index.tsx
- src/layout/TopBar/index.tsx
- src/locals/Zh/zh.json
- src/model/user.ts
- src/utils/utils.ts
> Feat: support the telemetry data collection

- src/extends/KV/index.tsx
> Fix: the additional parameter does not take effect

- .github/CODEOWNERS
- OWNERS
> Chore: add wangbow as an approver

- package.json
- src/utils/locale.tsx
Signed-off-by: Manuel Ruck <git@manuelruck.de>
Fixes #
I have:
> Fix: Fallback local language to en if not supported

- src/pages/ApplicationStatus/index.less
- src/pages/ApplicationStatus/index.tsx
> Fix: show application trait status

- src/layout/DefinitionDetails/index.tsx
- src/locals/Zh/zh.json
- src/pages/Definitions/index.tsx
- src/pages/UiSchema/index.less
- src/pages/UiSchema/index.tsx
Fixes definition management ui update
I have:
> Fix: definition management ui update

- src/extends/KV/index.tsx
> Fix: helmValues component support custom the configuration key

- src/extends/KV/index.tsx
* Feat: helmValues component support custom the configuration key
* Fix: kv value type update
* Fix: helm select kv update
Co-authored-by: wb-wb665667 <wb-wb665667@alibaba-inc.com>
> Fix: helmValues component support custom the configuration key (#494)

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- package.json
> Chore: add the issue templates

- src/common.less
- src/extends/HelmValues/index.tsx
- src/interface/application.ts
- src/layout/Application/components/Menus/index.tsx
- src/layout/Application/index.tsx
- src/locals/Zh/zh.json
- src/pages/ApplicationConfig/components/ComponentDialog/index.tsx
- src/pages/ApplicationConfig/components/Components/index.less
- src/pages/ApplicationConfig/components/Components/index.tsx
- src/pages/ApplicationInstanceList/index.tsx
- src/pages/ApplicationStatus/index.tsx
- src/pages/UiSchema/index.tsx
Fixes #500
Fixes #504 
I have:
> Feat: display the instances of both cloud service and common components

- src/pages/UiSchema/index.tsx
Fixes optimize the yamle input experience
I have:
> Fix: optimize the yamle input experience

- src/common.less
- src/locals/Zh/zh.json
- src/pages/Definitions/components/SelectSearch/index.less
- src/pages/Definitions/components/SelectSearch/index.tsx
- src/pages/Definitions/index.tsx
Fixes: definition management add type search function
I have:
> Feat: definition management add type search function

- src/locals/Zh/zh.json
- src/pages/Definitions/components/SelectSearch/index.tsx
- src/pages/UiSchema/index.less
- src/pages/UiSchema/index.tsx
> Feat: optimize the ui schema page

- src/components/UISchema/index.tsx
- src/extends/PolicySelect/index.tsx
- src/interface/application.ts
- src/pages/ApplicationWorkflow/workflow-component/index.tsx
- src/pages/ApplicationWorkflow/workflow-item/index.tsx
- src/pages/ApplicationWorkflow/workflow-item/workflow-form.tsx
- src/pages/UiSchema/index.less
> Fix: add PolicySelect component to support select the policy in deploy workflow step

- src/components/UISchema/index.tsx
- src/extends/PolicySelect/index.tsx
- src/interface/application.ts
- src/locals/Zh/zh.json
- src/pages/UiSchema/index.tsx
> Feat: optimize the ui schema component

- src/common.less
- src/pages/ApplicationConfig/components/ComponentDialog/index.tsx
- src/pages/ApplicationConfig/components/TraitDialog/index.tsx
- src/pages/ApplicationList/components/AddAppDialog/index.tsx
- src/pages/ApplicationWorkflow/workflow-item/workflow-form.tsx
- src/pages/Integrations/components/CreateIntegrationDialog/index.tsx
> Fix: component parameters are mixed after the component type is changed

- src/pages/ApplicationConfig/components/ComponentDialog/index.tsx
> Fix: component dependOn issue

- src/extends/KV/index.tsx
> Fix: fail to confige the helm value

- package.json
- src/api/observation.ts
- src/components/DefinitionCode/index.tsx
- src/pages/ApplicationStatus/components/ApplicationGraph/index.tsx
- src/pages/ApplicationStatus/components/ApplicationGraph/resource-show.tsx
- src/pages/ApplicationStatus/index.tsx
> Fix: incorrect display of resource details

- src/components/Permission/index.ts
- src/components/TreeGraph/index.less
- src/components/TreeGraph/index.tsx
- src/components/TreeGraph/utils.tsx
- src/interface/observation.ts
- src/layout/Application/components/AddAndEditEnvBind/index.tsx
- src/pages/ApplicationConfig/components/Components/index.tsx
- src/pages/ApplicationList/components/AddAppDialog/index.tsx
- src/pages/ApplicationList/components/CardContent/index.tsx
- src/pages/ApplicationList/components/GeneralConfig/index.tsx
- src/pages/ApplicationList/index.tsx
- src/pages/EnvPage/components/EnvDialog/index.tsx
- src/pages/EnvPage/components/List/index.tsx
- src/pages/EnvPage/index.tsx
- src/pages/ProjectApplications/index.tsx
- src/pages/ProjectRoles/components/Menu/index.tsx
> Fix: optimize permission check

- src/extends/PolicySelect/index.tsx
> Fix: fail to set the policy value

- src/api/application.ts
- src/components/Permission/index.ts
- src/components/TreeGraph/utils.tsx
- src/extends/K8sObjectsCode/index.tsx
- src/extends/K8sObjectsCode/objects.tsx
- src/layout/Application/components/EnvTabs/index.tsx
- src/pages/ApplicationConfig/components/PolicyList/index.tsx
- src/pages/ApplicationConfig/index.tsx
- src/pages/ApplicationInstanceList/components/Header/index.tsx
- src/pages/ApplicationStatus/index.tsx
> Feat: Optimize the kubernetes object editing component

- src/components/TreeGraph/index.less
- src/components/TreeGraph/index.tsx
- src/components/TreeGraph/utils.tsx
> Feat: change the title to Balloon

- src/locals/Zh/zh.json
- src/pages/ApplicationStatus/components/ApplicationGraph/index.tsx
- src/pages/ApplicationStatus/index.tsx
> Feat: default show the overview tab on the application status page

- src/layout/LeftMenu/menu.js
- src/pages/ApplicationInstanceList/components/PodDetail/index.tsx
- src/pages/ApplicationInstanceList/index.less
- src/pages/ApplicationInstanceList/index.tsx
- src/pages/Definitions/index.tsx
1. Optimize the permission of the definition management page.
2. Fix the nil bug in the instance page.
I have:
> Fix: optimize the permission of the definition management page

- src/interface/observation.ts
- src/pages/ApplicationInstanceList/index.tsx
Refer to https://github.com/kubevela/terraform-controller/pull/318
I have:
/cc @zzxwill
> Fix: get the region from status

- .github/workflows/release.yaml
- Dockerfile
- config/env.js
- package.json
- src/layout/LeftMenu/index.tsx
> Chore: get version from env

- .github/workflows/release.yaml
- Dockerfile
- config/env.js
- package.json
- src/layout/LeftMenu/index.tsx
- src/pages/Addons/components/detail/index.tsx
> Fix: Extra comma in addon pager (#542)

- src/layout/Application/components/WorkflowStep/index.tsx
- src/pages/Addons/components/card-conten/index.less
- src/pages/Addons/components/card-conten/index.tsx
- src/pages/ApplicationConfig/index.tsx
- src/pages/ApplicationList/components/CardContent/index.tsx
- src/pages/ApplicationList/components/EditAppDialog/index.tsx
1. Support editing the application labels
2. Sort addons based on enabled state
3. Fix the workflow record shown bug
Fixes #
I have:
> Feat: support edit the application labels

- package.json
- src/api/repository.ts
- src/components/UISchema/index.tsx
- src/extends/HelmChartSelect/index.tsx
- src/extends/HelmChartVersionSelect/index.tsx
- src/extends/HelmRepoSelect/index.tsx
- src/extends/HelmValues/index.tsx
- src/extends/ImageInput/index.less
- src/extends/ImageInput/index.tsx
- src/extends/ImageSecretSelect/index.tsx
- src/interface/application.ts
- src/interface/repository.ts
- src/locals/Zh/zh.json
- src/pages/Integrations/components/CreateIntegrationDialog/index.tsx
- src/pages/Integrations/index.tsx
- src/utils/_test/permission.test.ts
- src/utils/common.ts
- yarn.lock
> Feat: support to view the image info

- src/pages/TargetList/components/TargetDialog/index.tsx
- src/pages/TargetList/index.tsx
> Feat: Creating target support to select from all projects

- package.json
- src/api/application.ts
- src/interface/application.ts
- src/pages/ApplicationRevisionList/components/Detail/index.tsx
- src/pages/ApplicationRevisionList/components/List/index.tsx
- src/pages/ApplicationRevisionList/index.tsx
- yarn.lock
Fixes #526
Fixes #527 
I have:
> Feat: support to query and show the application configuration

- package.json
- src/api/productionLink.ts
- src/api/users.ts
- src/components/UISchema/index.tsx
- src/extends/ImageInput/index.tsx
- src/interface/user.ts
- src/layout/Application/components/Header/index.tsx
- src/layout/CloudShell/index.less
- src/layout/CloudShell/index.tsx
- src/layout/TopBar/index.tsx
- src/locals/Zh/zh.json
- src/model/addons.js
- src/model/cloudshell.js
- src/pages/Addons/index.tsx
- src/pages/ApplicationConfig/components/ComponentDialog/index.tsx
- src/pages/Login/index.tsx
- src/utils/cache.ts
- web.conf
> Feat: add the CloudShell feature

- src/pages/ApplicationInstanceList/components/ContainerLog/index.tsx
- src/pages/ApplicationLog/components/LogContainer/index.tsx
> Fix: show the error message of querying the logs

- .github/workflows/release.yaml
> Revert "Feat: add arm64 image build"

- src/layout/CloudShell/index.tsx
> Fix: the cloudshell url is invalid

- .github/workflows/release.yaml
Signed-off-by: qiaozp <chivalry.pp@gmail.com>
This complete the arm64 image build for #560 
Image build problem is solved. Test run [here](https://github.com/kubevela/velaux/runs/7166938411?check_suite_focus=true)
Fixes #
I have:
> Feat: add arm64 image build

- src/pages/TargetList/components/TargetDialog/index.tsx
Signed-off-by: qiaozp <chivalry.pp@gmail.com>
Fixes #
I have:
> Fix: don't load provider list with default project

- src/pages/Integrations/components/CreateIntegrationDialog/index.tsx
> Fix: the integration name is required

- package.json
- src/api/application.ts
- src/common.less
- src/components/ApplicationDiff/index.less
- src/components/ApplicationDiff/index.tsx
- src/interface/application.ts
- src/layout/Application/components/Header/index.tsx
- src/layout/TopBar/index.tsx
- src/locals/Zh/zh.json
- src/pages/ApplicationInstanceList/components/Header/index.tsx
- src/pages/ApplicationLog/components/LogContainer/index.tsx
- src/pages/ApplicationRevisionList/components/List/index.tsx
- src/pages/ApplicationStatus/index.tsx
- src/pages/Users/index.less
- yarn.lock
If there is diff, will show the button, then clicking it could show the different.
Fixes #502 
I have:
> Feat: support to show the application diff

- src/api/application.ts
- src/components/ApplicationDryRun/index.less
- src/components/ApplicationDryRun/index.tsx
- src/interface/application.ts
- src/layout/Application/components/DeployConfig/index.less
- src/layout/Application/components/DeployConfig/index.tsx
- src/layout/Application/components/Header/index.tsx
- src/locals/Zh/zh.json
> Feat: support dry run the application

- src/pages/Addons/components/card-conten/index.tsx
- src/pages/Addons/components/search/index.less
- src/pages/Addons/components/search/index.tsx
- src/pages/Addons/index.tsx
- src/utils/common.ts
I have:
/cc @wangyikewxgm  @Somefive
> Feat: support to filter the addons by the tags

- src/locals/Zh/zh.json
- src/pages/ApplicationList/components/CardContent/index.tsx
- src/pages/ApplicationList/components/SelectSearch/index.less
- src/pages/ApplicationList/components/SelectSearch/index.tsx
- src/pages/ApplicationList/index.tsx
- src/pages/EnvPage/components/List/index.tsx
- src/pages/ProjectApplications/components/SelectSearch/index.tsx
- src/pages/ProjectApplications/index.tsx
- src/pages/ProjectSummary/components/General/index.tsx
- src/pages/ProjectSummary/components/Targets/index.tsx
Fixes: kubevela/kubevela#4245
I have:
> Feat: support show the application list with the table

- src/layout/Project/index.tsx
- src/layout/TopBar/index.tsx
- src/locals/Zh/zh.json
- src/pages/ProjectSummary/components/Integrations/index.tsx
- src/pages/ProjectSummary/components/Targets/index.tsx
- src/pages/ProjectSummary/index.tsx
- src/pages/TargetList/components/TargetDialog/index.tsx
- src/pages/Users/components/CreateUser/index.tsx
> Feat: support to show my projects

- src/components/CustomSelect/index.tsx
- src/extends/SecretKeySelect/index.tsx
- src/extends/SecretSelect/index.tsx
- src/interface/observation.ts
- src/utils/locale.tsx
> Feat: support to custom input the secret name and key

- .github/CODEOWNERS
- OWNERS
> Chore: change the owner

- src/pages/ApplicationRevisionList/components/List/index.tsx
- src/pages/ApplicationRevisionList/index.less
- src/pages/ApplicationRevisionList/index.tsx
> Fix: optimize the revision pagination and status show

- src/common.less
- src/layout/Application/components/DeployConfig/index.tsx
- src/layout/Application/components/EnvTabs/index.tsx
- src/layout/Application/components/Header/index.tsx
- src/layout/Application/components/Menus/index.less
- src/layout/Application/components/WorkflowSlider/index.less
- src/layout/Application/components/WorkflowSlider/index.tsx
- src/layout/Application/components/WorkflowStep/index.less
- src/layout/Application/components/WorkflowStep/index.tsx
- src/layout/Application/index.less
- src/locals/Zh/zh.json
- src/pages/ApplicationConfig/components/PolicyList/index.tsx
- src/pages/ApplicationConfig/index.less
- src/pages/ApplicationConfig/index.tsx
- src/pages/ApplicationInstanceList/components/Header/index.tsx
- src/pages/ApplicationList/components/SelectSearch/index.less
- src/pages/ApplicationList/components/SelectSearch/index.tsx
- src/pages/ApplicationRevisionList/components/Hearder/index.tsx
> Feat: Optimize the application configuration page

- CONTRIBUTING.md
- docs/contributing/velaux.md
> Chore: update the contributing document

- src/layout/Application/index.less
- src/pages/ApplicationInstanceList/index.tsx
- src/pages/ApplicationRevisionList/components/List/index.tsx
> Fix: optimize the styles

- src/components/PlatformSetting/index.tsx
- src/interface/system.ts
- src/pages/Login/index.tsx
Reference: https://github.com/kubevela/kubevela/pull/4429
I have:
> Feat: support to test authentication with dex

- src/api/application.ts
- src/interface/application.ts
- src/pages/ApplicationConfig/components/PolicyDialog/index.tsx
- src/pages/ApplicationConfig/components/PolicyList/index.tsx
- src/pages/ApplicationConfig/index.tsx
> Feat: support to update the policy

- src/components/CustomSelect/index.tsx
- src/components/PlatformSetting/index.tsx
- src/interface/system.ts
Reference: https://github.com/kubevela/kubevela/pull/4431
I have:
> Feat: support to set the default roles

- src/components/TreeGraph/index.tsx
- src/interface/project.ts
- src/pages/ApplicationStatus/components/ApplicationGraph/index.tsx
- src/pages/ProjectMembers/index.tsx
> Feat: support to show the member alias and show the detail of the pod and application

- src/pages/ApplicationInstanceList/components/PodDetail/index.tsx
- src/pages/ApplicationInstanceList/index.less
- src/utils/common.ts
> Feat: support to show the console shell button

- src/layout/TopBar/components/EditPlatFormUserDialog/index.tsx
- src/pages/ApplicationInstanceList/components/PodDetail/index.tsx
- src/pages/Users/components/CreateUser/index.tsx
- src/utils/common.ts
> Fix: the email can not edit

- src/pages/Login/index.tsx
> Fix: incorrect dex redirect URL

- src/layout/TopBar/components/EditPlatFormUserDialog/index.tsx
- src/pages/ApplicationInstanceList/components/PodDetail/index.tsx
- src/pages/Users/components/CreateUser/index.tsx
- src/utils/common.ts
> Fix: the email can not edit (#600)

- src/pages/Addons/components/card-conten/index.tsx
- src/pages/Addons/components/detail/index.tsx
- src/pages/ApplicationInstanceList/components/Header/index.tsx
- src/pages/CallBackPage/index.tsx
- src/pages/NotFound/index.tsx
> Feat: show the endpoints in the addon detail page

- src/layout/TopBar/components/EditPlatFormUserDialog/index.tsx
- src/pages/Cluster/components/CloudServiceDialog/index.less
- src/pages/Cluster/components/CloudServiceDialog/index.tsx
- src/utils/resetLogin.ts
- src/utils/utils.ts
> Fix: set the locale

- src/components/UISchema/index.tsx
- src/extends/Group/index.tsx
- src/locals/Zh/zh.json
Fixes kubevela/kubevela#4647
I have:
> Fix: miss the form items after turning off the switch

- src/pages/ApplicationRevisionList/components/Detail/index.tsx
> Fix: can not show the detail of the first revision (#612)

- src/interface/observation.ts
- src/layout/Application/components/AddAndEditEnvBind/index.tsx
- src/locals/Zh/zh.json
- src/pages/Addons/components/detail/index.tsx
- src/pages/ApplicationConfig/components/TriggerDialog/index.tsx
- src/pages/ApplicationInstanceList/components/Header/index.tsx
- src/pages/ApplicationList/components/AddAppDialog/index.tsx
- src/pages/Cluster/components/AddClustDialog/index.tsx
- src/pages/Cluster/components/ClustSelectSearch/index.less
- src/pages/Cluster/components/ClustSelectSearch/index.tsx
- src/pages/Cluster/index.tsx
- src/pages/EnvPage/components/EnvDialog/index.tsx
- src/pages/EnvPage/components/List/index.tsx
- src/pages/EnvPage/index.less
- src/pages/EnvPage/index.tsx
- src/pages/TargetList/components/Namespace/index.less
- src/pages/TargetList/components/Namespace/index.tsx
- src/pages/TargetList/components/TargetDialog/index.tsx
- src/pages/TargetList/index.less
- src/pages/TargetList/index.tsx
- src/utils/utils.ts
> Feat: support to create the target where creating the environment

- src/layout/LeftMenu/index.less
- src/layout/LeftMenu/index.tsx
- src/layout/index.less
> Feat: display the version info more directly

- src/components/TreeGraph/component-node.less
- src/components/TreeGraph/component-node.tsx
- src/components/TreeGraph/index.less
- src/components/TreeGraph/index.tsx
- src/components/TreeGraph/interface.tsx
- src/components/TreeGraph/utils.tsx
- src/components/UISchema/index.tsx
- src/interface/application.ts
- src/interface/observation.ts
- src/pages/ApplicationStatus/components/ApplicationGraph/index.less
- src/pages/ApplicationStatus/components/ApplicationGraph/index.tsx
- src/pages/ApplicationStatus/index.tsx
> Fix: enhance the application graph

- src/utils/utils.ts
> Fix: support to open the tcp address directly

- src/layout/TopBar/components/EditPlatFormUserDialog/index.tsx
- src/pages/PipelineListPage/components/CreatePipeline/index.tsx
- src/pages/PipelineListPage/index.less
- src/pages/PipelineListPage/index.tsx
> Fix: guides the user to enable the vale-workflow addon

- src/pages/PipelineListPage/components/CreatePipeline/index.tsx
- src/pages/PipelineListPage/components/CreatePipeline/pipeline-template.ts
> Feat: add the observability Pipeline template

- src/api/config.ts
- src/components/Drawer/index.less
- src/components/Drawer/index.tsx
- src/locals/Zh/zh.json
- src/pages/PipelineListPage/index.tsx
- src/pages/ProjectSummary/components/ConfigDistribution/index.tsx
> Feat: add some translations and support to delete the distribution

- src/locals/Zh/zh.json
Signed-off-by: wzjgo <wzjgo1023@gmail.com>
Docs #
I have:
> Docs: translate into chinese

- src/interface/application.ts
- src/pages/ApplicationConfig/components/TriggerDialog/index.tsx
> Feat: support to set the registry for the ACR webhook

- src/pages/ApplicationList/components/AddAppDialog/index.tsx
> Fix: the wrong environment list was loaded

- src/interface/addon.ts
- src/pages/Addons/components/detail/index.tsx
> Fix: enable the addon with the registry name

- src/pages/Configs/components/CreateConfigDialog/index.tsx
> Feat: show the notification message after creating a config

- src/extends/ImageSecretSelect/index.tsx
> Fix: the page crash when input by keyboard

- src/pages/EnvPage/components/List/index.tsx
> Fix: failed to check the permissions of the environment

- src/api/application.ts
- src/api/definitions.ts
- src/components/ApplicationDiff/index.less
- src/components/ApplicationDiff/index.tsx
- src/components/DiffEditor/index.tsx
- src/interface/application.ts
- src/model/application.js
- src/pages/ApplicationConfig/components/ComponentDialog/index.tsx
- src/pages/ApplicationConfig/components/PolicyDialog/index.tsx
- src/pages/ApplicationConfig/components/TraitDialog/index.tsx
- src/pages/ApplicationConfig/components/TriggerDialog/index.tsx
- src/pages/ApplicationConfig/index.tsx
- src/pages/ApplicationInstanceList/components/Header/index.tsx
- src/pages/ApplicationList/components/AddAppDialog/index.tsx
- src/pages/ApplicationList/index.tsx
- src/pages/ApplicationRevisionList/components/List/index.tsx
- src/pages/ApplicationRevisionList/index.tsx
- src/pages/ApplicationWorkflowStatus/components/WorkflowRecord/index.tsx
- src/pages/Configs/components/CreateConfigDialog/index.tsx
- src/pages/PipelineRunPage/components/Header/index.tsx
- src/pages/ProjectApplications/index.tsx
- src/pages/ProjectSummary/components/ConfigDistribution/index.tsx
- src/pages/ProjectSummary/components/Configs/index.tsx
Check the differences before rollbacking.
I have:
> Feat: support to rollback the application

- src/interface/application.ts
- src/layout/Application/index.tsx
- src/pages/Addons/components/detail/index.tsx
- src/pages/ApplicationWorkflowStatus/index.tsx
> Fix: enhance the addon detail page

- package.json
- src/components/WorkflowStudio/type-select.tsx
- src/locals/Zh/zh.json
- src/pages/ApplicationWorkflowStatus/index.tsx
- src/pages/ApplicationWorkflowStudio/index.tsx
- src/pages/PipelineListPage/components/CreatePipeline/index.tsx
- src/pages/PipelineStudio/index.tsx
> Fix: add some local configs

- src/common.less
- src/components/ApplicationDiff/index.tsx
- src/layout/Content/index.tsx
- src/pages/Addons/components/detail/index.tsx
- src/pages/ApplicationConfig/components/Components/index.tsx
- src/pages/ApplicationConfig/components/TriggerList/index.tsx
- src/pages/ApplicationConfig/index.tsx
- src/pages/ApplicationEnvRoute/index.tsx
- src/pages/ApplicationRevisionList/components/List/index.tsx
- src/pages/EnvPage/components/List/index.tsx
> Feat: add the envbinding route page

- src/api/application.ts
- src/layout/Application/components/AddAndEditEnvBind/index.tsx
Fixes kubevela/kubevela#5371
I have:
> Fix: can not binding the environment

- src/common.less
Make some small edit to the page display of application.
Old:
New:
Fixes #
I have:
> Fix: optimize some application page display

- src/components/WorkflowStudio/step.tsx
- src/components/WorkflowStudio/type-select.tsx
- src/components/WorkflowYAML/index.tsx
- src/layout/Application/components/EnvTabs/index.less
- src/layout/Application/components/EnvTabs/index.tsx
- src/layout/Application/components/Header/index.tsx
- src/locals/Zh/zh.json
- src/pages/ApplicationWorkflowStatus/components/WorkflowRecord/index.tsx
- src/pages/ApplicationWorkflowStudio/index.tsx
- src/pages/PipelineRunPage/index.less
- src/pages/PipelineRunPage/index.tsx
- src/pages/PipelineStudio/index.tsx
> Feat: optimize the style and support to delete the group step

- src/api/pipeline.ts
- src/components/RunPipeline/index.less
- src/components/RunPipeline/index.tsx
- src/components/RunPipeline/new-context.tsx
- src/extends/KV/index.tsx
- src/locals/Zh/zh.json
- src/pages/PipelineListPage/components/CreatePipeline/index.tsx
- src/pages/PipelineListPage/components/CreatePipeline/pipeline-template.ts
- src/pages/PipelineListPage/components/PipelineClone/index.tsx
- src/pages/PipelineListPage/index.tsx
> Feat: support to update, clone, and edit the pipeline context

- src/api/application.ts
- src/interface/application.ts
- src/layout/Application/components/AddAndEditEnvBind/index.tsx
- src/locals/Zh/zh.json
- src/pages/ApplicationConfig/components/Components/index.less
- src/pages/ApplicationConfig/components/Components/index.tsx
- src/pages/ApplicationConfig/components/TriggerDialog/index.tsx
- src/pages/ApplicationConfig/components/TriggerList/index.less
- src/pages/ApplicationConfig/components/TriggerList/index.tsx
- src/pages/ApplicationConfig/index.tsx
- src/pages/ApplicationList/components/AddAppDialog/index.tsx
- src/utils/common.ts
Fixes https://github.com/kubevela/kubevela/issues/5373
I have:
> Feat: support for updating the trigger

- src/components/PipelineGraph/index.tsx
- src/locals/Zh/zh.json
- src/pages/ApplicationWorkflowStatus/components/WorkflowRecord/index.tsx
- src/pages/PipelineRunPage/components/Header/index.tsx
- src/pages/PipelineRunPage/index.tsx
> Fix: Step repetition rendering

- src/components/NumItem/index.tsx
- src/layout/Application/components/Menus/index.tsx
- src/layout/Content/index.tsx
- src/pages/ApplicationConfig/index.tsx
- src/pages/ApplicationRevisionList/index.tsx
- src/pages/ApplicationWorkflowList/index.tsx
> Feat: support for deleting the workflow

- packages/velaux-ui/src/services/PluginService.ts
> Fix: Can't render the menus when there is no plugins

- packages/velaux-ui/src/layout/Header/components/EditPlatFormUserDialog/index.tsx
> Feat: add button loading style

- .github/workflows/issue-commands.yml
> Feat: add kubevela bot in github workflow

- packages/velaux-ui/src/pages/ApplicationInstanceList/components/Header/index.tsx
- packages/velaux-ui/src/pages/ApplicationInstanceList/index.tsx
- packages/velaux-ui/src/pages/ApplicationStatus/index.tsx
- packages/velaux-ui/src/pages/ApplicationWorkflowStatus/index.tsx
> Feat: Add the header for the workflow status page

- packages/velaux-ui/src/extends/HelmRepoSelect/index.tsx
- packages/velaux-ui/src/pages/ApplicationList/components/AddAppDialog/index.tsx
- packages/velaux-ui/src/pages/Configs/components/CreateConfigDialog/index.tsx
- pkg/server/server.go
> Fix: Can't create the config

- addon/metadata.yaml
- addon/resources/server.cue
- packages/velaux-ui/src/pages/ApplicationList/components/CardContent/index.tsx
- packages/velaux-ui/src/pages/ApplicationList/index.tsx
> Fix: Page crashed when there is no application

- packages/velaux-ui/src/pages/ApplicationWorkflowStatus/index.tsx
> Fix: Load the workflow by the record

- e2e-test/application_test.go
- packages/velaux-ui/src/interface/application.ts
- packages/velaux-ui/src/locals/Zh/zh.json
- packages/velaux-ui/src/pages/ApplicationConfig/index.tsx
- packages/velaux-ui/src/pages/ApplicationList/components/EditAppDialog/index.tsx
- pkg/server/domain/model/application.go
- pkg/server/domain/service/application.go
- pkg/server/interfaces/api/assembler/v1/do2dto.go
- pkg/server/interfaces/api/dto/v1/types.go
> Fix: Add custom annotation add for application edit page

- Dockerfile.local
- Makefile
- packages/velaux-ui/src/layout/LeftMenu/index.tsx
- packages/velaux-ui/src/locals/Zh/zh.json
- packages/velaux-ui/src/pages/PlatformSetting/index.tsx
- pkg/server/domain/service/authentication.go
> Fix: Can't submit the platform settings

- packages/velaux-ui/src/components/TreeGraph/component-node.tsx
Application Graph displays exception stack trace
Fixes #793
I have:
> Fix: Application Graph displays exception stack trace

- .github/CODEOWNERS
> Chore: Add @chivalryq and @wangyikewxgm as the code owner

- packages/velaux-ui/src/locals/Zh/zh.json
- packages/velaux-ui/src/pages/ApplicationConfig/components/PolicyDialog/index.tsx
> Fix: Show policy type when editing the policy

- packages/velaux-ui/src/pages/Users/components/CreateUser/index.tsx
> Fix: User can't be updated

- .github/workflows/issue-commands.yml
- .github/workflows/staticcheck.yaml
> Feat: add CI auto restart command

- .github/workflows/server-test.yml
- e2e-test/velaql_test.go
> Fix: server test fails for k3d version
